logging:
  format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
  level: 30
bot:
  token:
  commands:
    help:
      message: |
        /help: ä½¿ç”¨èªªæ˜
        /meow: å–µ~
        /chance (äº‹é …1 äº‹é …2 äº‹é …3...) é è¨€å®¶: æ±‚ç™¼ç”Ÿæ©Ÿç‡
        /fortune (äº‹é …1 äº‹é …2 äº‹é …3...) å åœå¸«: å¤§å‰orå¤§å‡¶?
        /pick (é¸é …1 é¸é …2 é¸é …3...) æ©Ÿå™¨å–µé»é»å
    meow:
      choices:
        å–µ: 1
        å–µ~: 1
        meow~: 1
        meow: 1
        ğŸ˜º: 1
        ğŸ˜¸: 1
        ğŸ±: 1
    chance:
      min: 10
      max: 90
    fortune:
      choices:
        å¤§å‰: 5
        å‰: 10
        å°å‰: 20
        å°šå¯: 30
        å°å…‡: 20
        å…‡: 10
        å¤§å‡¶: 5
